export const PERMISSION = {
  MEMBERS_VIEW: "members.view",
  MEMBERS_INVITE: "members.invite",
  MEMBERS_MANAGE: "members.manage",

  EXPENSES_VIEW: "expenses.view",
  EXPENSES_CREATE: "expenses.create",
  EXPENSES_EDIT: "expenses.edit",
  EXPENSES_DELETE: "expenses.delete",
  EXPENSES_APPROVE: "expenses.approve",

  MEALS_VIEW: "meals.view",
  MEALS_CREATE: "meals.create",
  MEALS_EDIT: "meals.edit",
  MEALS_MANAGE: "meals.manage",

  PAYMENTS_VIEW: "payments.view",
  PAYMENTS_CREATE: "payments.create",
  PAYMENTS_EDIT: "payments.edit",

  REPORTS_VIEW: "reports.view",
  REPORTS_EXPORT: "reports.export",

  SETTINGS_VIEW: "settings.view",
  SETTINGS_MANAGE: "settings.manage",

  ACCOUNTING_FINALIZE: "accounting.finalize",
  ACCOUNTING_CLOSE: "accounting.close",
  SETTLEMENT_MANAGE: "settlement.manage",
} as const;
export type Permission = (typeof PERMISSION)[keyof typeof PERMISSION];

export const ALL_PERMISSIONS: readonly Permission[] = Object.values(PERMISSION);

export const ADMIN_PERMISSIONS: readonly Permission[] = [
  PERMISSION.MEMBERS_VIEW,
  PERMISSION.MEMBERS_INVITE,
  PERMISSION.MEMBERS_MANAGE,
  PERMISSION.EXPENSES_VIEW,
  PERMISSION.EXPENSES_CREATE,
  PERMISSION.EXPENSES_EDIT,
  PERMISSION.EXPENSES_DELETE,
  PERMISSION.EXPENSES_APPROVE,
  PERMISSION.MEALS_VIEW,
  PERMISSION.MEALS_CREATE,
  PERMISSION.MEALS_EDIT,
  PERMISSION.MEALS_MANAGE,
  PERMISSION.PAYMENTS_VIEW,
  PERMISSION.PAYMENTS_CREATE,
  PERMISSION.PAYMENTS_EDIT,
  PERMISSION.REPORTS_VIEW,
  PERMISSION.REPORTS_EXPORT,
  PERMISSION.SETTINGS_VIEW,
  PERMISSION.SETTINGS_MANAGE,
  PERMISSION.ACCOUNTING_FINALIZE,
  PERMISSION.ACCOUNTING_CLOSE,
  PERMISSION.SETTLEMENT_MANAGE,
];

export const MEMBER_PERMISSIONS: readonly Permission[] = [
  PERMISSION.EXPENSES_VIEW,
  PERMISSION.EXPENSES_CREATE,
  PERMISSION.MEALS_VIEW,
  PERMISSION.MEALS_CREATE,
  PERMISSION.PAYMENTS_VIEW,
  PERMISSION.PAYMENTS_CREATE,
  PERMISSION.REPORTS_VIEW,
];
